package com.example.bot_diary.models;

public enum UserState {
    NONE,
    AWAITING_TASK_DESCRIPTION,
    TASK_CREATED,
    AWAITING_NOTIFICATION_DATE,
    SELECT_DATE, AWAITING_NOTIFICATION_TIME,
    DATETIME_UPDATE

}